### ISSUE TITLE
Error loading data from c-trap h5

### ISSUE THREAD

**Issue by BenjaminAmbrose** [REMI-HIRI/POTATO#3]
Hi,

I have tried to use your software to analyse some c-trap data but when I attempt to load an h5 file in the single file viewer I get the following error in the terminal 

`Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "POTATO_GUI.py", line 1042, in <lambda>
  File "POTATO_GUI.py", line 282, in get_single_file
  File "POTATO_ForceRamp.py", line 59, in read_in_data
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`

I also get the following when I try to use folder analysis:

`Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "POTATO_ForceRamp.py", line 133, in start_subprocess
  File "POTATO_ForceRamp.py", line 55, in read_in_data
  File "POTATO_preprocessing.py", line 10, in preprocess_RAW
TypeError: 'NoneType' object is not subscriptable`

Best,
Ben

**Comment by lpekarek** [comment]
Hi Ben, 

Thank you for your feedback! Sometimes with the updates from Lumicks, the H5 file structure changes a bit etc. 

One possible thing that comes to my mind is whether you have properly selected the high-frequency (HF) or low-frequency (LF) option. In other words, do you use the piezo tracking option to gather your data? If not, then make sure you select the low-frequency option. 

If this does not help, could you share the h5 file with us? 

I hope this helps! 

Best wishes, Lukáš

**Comment by BenjaminAmbrose** [comment]
Hi Lukáš

I've checked the file with hdf5viewer and it contains both HF and LF data. I've attached a sample file for you to take a look at,

Let me know if you can find the problem

Best,
Ben 

[20230228-163620 DNA3 FD Curve 8.zip](https://github.com/REMI-HIRI/POTATO/files/11936924/20230228-163620.DNA3.FD.Curve.8.zip)

**Comment by Gundura** [comment]
Hi Ben, 
the issue is as Lukáš predicted. There is a change in the h5 file structure to what POTATO was originally designed to handle. I can offer a "quick fix" in the code. The executable will take some time to adjust. If you run the code, you need an environment with an pandas version that is prior to 2.0. (I think 1.5 should be still fine). 

Also your file contains both, a forward and reverse curve. So you have to tick the "MultiH5" checkbox. I did find high frequency data only for the force, but not for the distance. Probably the Piezo Tracking was not enabled when this curve was measured, or it was moved somewhere else as well.

Best, Stefan
